### ISSUE TITLE
missing attachments 

### ISSUE THREAD

**Issue by eladda** [irontec/zmantis#4]
when export an email to mantis not all the attachments are include.

only the images on html code are exported

**Comment by eladda** [comment]
Hello Kaian,
I works with image files and PDF but not any times with Office Files or others.

It think exist a filter of importable file over mantis but I did not able to found it.

so this is not a zMantis problem but a Mantis one.

It would be good, if you know what is the way to configure Mantis to mark this issue as known and mantis related one given a short guideline.

If you know what is the file to configure I can prepare a sort of step by step guide

**Comment by Kaian** [comment]
Hi!

You can configure mantis from its configure include file (/path/to/mantis/config_defaults_inc.php)

    /**
     * Maximum number of files that can be uploaded simultaneously
     * @global int $g_file_upload_max_num
     */
    $g_file_upload_max_num = 1;

    /**
     * Maximum file size that can be uploaded
     * Also check your PHP settings (default is usually 2MBs)
     * @global int $g_max_file_size
     */
    $g_max_file_size        = 5000000;

    /**
     * Files that are allowed or not allowed.  Separate items by commas.
     * eg. 'php,html,java,exe,pl'
     * if $g_allowed_files is filled in NO other file types will be allowed.
     * $g_disallowed_files takes precedence over $g_allowed_files
     * @global string $g_allowed_files
     */
    $g_allowed_files        = '';

    /**
     *
     * @global string $g_disallowed_files
     */
    $g_disallowed_files     = '';

I think that's the default settings (allow all file extensions), so rejecting Office Files It's quite a strange behaviour.

Best regards

**Comment by Kaian** [comment]
Closed as not related with zMantis.
Don't hesitate to provide any other information or reopen the issue.

Thanks!
